name = "SomaticPhylogenies"
uuid = "9efb0cad-9742-421b-a846-1625b166c99a"
authors = ["Matthias Günther <ma.guenther@dkfz.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
